### ISSUE TITLE
请问diff的计算是严格按照diff=(np.abs(data1) - np.abs(data2)).mean()来计算的吗

### ISSUE THREAD

**Issue by daidaiershidi** [WenmuZhou/reprod_log#4]
```
    diff_helper = ReprodDiffHelper()
    # 读取info
    torch_info = diff_helper.load_info('loss_torch.npy')
    paddle_info = diff_helper.load_info('loss_paddle.npy')
    # 比较info
    diff_helper.compare_info(torch_info, paddle_info)
    # 手动计算
    print('手动计算diff:', np.mean(np.abs(torch_info['stage_2:d']) - np.abs(paddle_info['stage_2:d'])))
    # 
    diff_helper.report(diff_method="mean", path='loss_diff.log')
```
手动计算diff: 9.908756e-10
[2022/01/07 07:54:06] root INFO: stage_2:d: 
[2022/01/07 07:54:06] root INFO:        mean diff: check passed: False, value: 0.1399555653333664
----------------------------------------------------------------------------------------------------------------------------------
字典里其他的值我也有手动计算，结果也不一样，但没有这个例子差别这么大（check paessed true和false的区别）

**Comment by WenmuZhou** [comment]
可以参考这一行https://github.com/WenmuZhou/reprod_log/blob/master/reprod_log/compare.py#L47
